/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/renderer/astryx-theme/makaTheme.ts
 * Command: astryx theme build src/renderer/astryx-theme/makaTheme.ts --out src/renderer/astryx-theme/maka.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.1.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/AppShell' {
  interface AppShellVariantMap {
    'elevated': true;
  }
}
